# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fundmore
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: advanced
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-crud-dynamodb

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1  # Replace with your desired AWS region
  environment:
    DYNAMODB_TABLE: product-table
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

resources:
  Resources:
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

